version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=example_user
      - MYSQL_PASSWORD=example_password
      - MYSQL_DATABASE=example_db
    ports:
      - '3000:3000'
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: example_user
      PMA_PASSWORD: example_password
      PMA_ARBITRARY: 1
      # MYSQL_ROOT_PASSWORD: example_password
    ports:
      - "8080:80"
    depends_on:
      - mysql